@baseUrl = http://localhost:3000
@Bearer = Bearer {{authentication.response.body.accessToken}}

######## USUÁRIOS

### Obter um usuário (me)
GET {{baseUrl}}/users/me
Content-Type: application/json
Authorization: {{Bearer}}

### Criar um novo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe Silva",
    "email": "john.doe9@example.com",
    "password": "securepassword"
}

### Atualizar um usuário por ID
PATCH {{baseUrl}}/users/3
Content-Type: application/json
Authorization: {{Bearer}}

{
    "name": "John Eldia",
    "password": "securepassword"
}

### Deletar um usuário por ID
DELETE {{baseUrl}}/users
Authorization: {{Bearer}}

######## Login
# @name authentication
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email": "john.doe2@example.com",
    "password": "securepassword"
}