@baseUrl = http://localhost:3000

######## USUÁRIOS

### Obter todos os usuários
GET {{baseUrl}}/users

### Obter um usuário por ID
GET {{baseUrl}}/users/3

### Criar um novo usuário
POST {{baseUrl}}/users
Content-Type: application/json

{
    "name": "John Doe Silva",
    "email": "john.doe2@example.com",
    "password": "securepassword"
}

### Atualizar um usuário por ID
PATCH {{baseUrl}}/users/3
Content-Type: application/json

{
    "name": "John Update",
    "password": "john.updated2@example.com"
}

### Deletar um usuário por ID
DELETE {{baseUrl}}/users/3

######## Login
POST {{baseUrl}}/auth
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "john.updated2@example.com"
}